// Generated by CoffeeScript 1.6.3
(function() {
  var fs, jade;

  fs = require('fs');

  jade = require('jade');

  module.exports = function(file, options, locals, cb) {
    return fs.readFile(file, 'utf8', function(err, data) {
      var build;
      if (err) {
        return cb(err);
      }
      build = jade.compile(data, options);
      if (cb) {
        return cb(build(locals));
      }
    });
  };

}).call(this);
