// Generated by CoffeeScript 1.6.3
(function() {
  var moment, _str;

  _str = require('underscore.string');

  moment = require('moment');

  module.exports = {
    Tasks: {
      model: {
        title: String,
        details: String,
        dueDate: Date,
        createdAt: {
          type: Date
        },
        _id: false,
        id: String,
        completed: {
          type: Boolean,
          "default": false
        }
      },
      methods: {},
      validators: {
        title: {
          fn: function(val) {
            return val.length > 3;
          },
          msg: 'Invalid title length.'
        }
      },
      virtuals: {},
      hooks: {
        pre: {
          save: function(next) {
            if (!this.id) {
              this.id = _str.slugify(this.title);
            }
            this.createdAt = Date.now();
            return next();
          }
        },
        post: {}
      },
      jsonOmit: ['_id'],
      webform: {
        hidden: ['id', 'createdAt'],
        textArea: ['details'],
        date: ['dueDate'],
        checkBox: [],
        radioBtn: [
          {
            'completed': {
              choices: ['true', 'false'],
              defaults: ['false']
            }
          }
        ],
        select: []
      }
    }
  };

}).call(this);
