// Generated by CoffeeScript 1.6.3
(function() {
  var io, setup, sockets;

  sockets = require('socket.io');

  setup = require('./setup');

  io = void 0;

  module.exports = {
    socket: function() {
      return io;
    },
    init: function(server) {
      if (io === void 0) {
        io = sockets.listen(server);
        io.set('log level', 1);
        io.set('origins', 'http://localhost:' + setup.serverPort);
        return io;
      }
    }
  };

}).call(this);
