// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var _ref;

  this.app = (_ref = window.app) != null ? _ref : {};

  require.config({
    paths: {
      'jquery': '/scripts/vendor/jquery/jquery.min',
      'moment': '/scripts/vendor/moment/min/moment.min',
      'underscore': '/scripts/vendor/lodash/dist/lodash.min',
      'underscore.string': '/scripts/vendor/underscore.string/dist/underscore.string.min',
      'utils': 'utils'
    },
    shim: {
      'underscore': {
        exports: '_'
      },
      'underscore.string': {
        deps: ['underscore'],
        init: function(_) {
          return _.mixin(_.str.exports());
        }
      }
    }
  });

  require(['utils', 'jquery', 'moment', 'underscore', 'underscore.string'], function(utils, $, moment) {
    'use strict';    return $(function() {
      var $approve, $btnNow, $btns, $cancel, $clear, $dds, $edit, $header, $labels, $submit, $trash, displayStatus;

      console.log('Peeking behind the curtains now, are you? @alvaromuir haz the codez.');
      $header = $('#header h2');
      $labels = $('label');
      $submit = $('#submit');
      $btns = $('.btn');
      $clear = $('#clear');
      $edit = $('#edit');
      $approve = $('#approve');
      $cancel = $('#cancel');
      $trash = $('#trash');
      $dds = $('dd');
      $btnNow = $('#btnNow');
      $labels.each(function() {
        return $(this).html(_.str.humanize($(this).html()));
      });
      $('form :first').css("visibility", "visible");
      displayStatus = function(sel, banner, msg) {
        $('.alert :first').addClass(sel);
        $('.alert :first strong').html(banner);
        $('.alert :first p').html(msg);
        return $('.alert :first').fadeToggle('slow');
      };
      app.currentFormData = {};
      $(document).on('click', function() {
        if ($('.alert :first').is(':visible')) {
          return $('.alert :first').fadeToggle(3000);
        }
      });
      $btns.on('click', function(e) {
        return e.preventDefault();
      });
      $clear.on('click', function() {
        return $(this).closest('form').find("input[type=text], textarea").val("");
      });
      $btnNow.on('click', function(e) {
        var $input;

        $input = $(this).prev('input:first');
        return $input.val(moment(new Date()).format('MMM DD YYYY'));
      });
      $submit.on('click', function(e) {
        var $form, apiRoot, path;

        path = window.location.pathname.split('/');
        apiRoot = path[path.length - 1];
        $form = $(this).parents('form:first');
        e.preventDefault();
        if ($form.serialize()) {
          return $.ajax({
            type: "POST",
            url: '/api/' + apiRoot,
            data: $form.serialize(),
            success: function(data) {
              $form.find("input[type=text], textarea").val("");
              if (data.error) {
                return displayStatus(null, 'WARNING', data.error.message);
              } else {
                return displayStatus('alert-success', 'All Good.', '"' + data.title + '" has been posted to the server.');
              }
            },
            error: function(err) {
              return displayStatus('alert-error', 'Code Red - Danger!', err.statusText);
            }
          });
        } else {
          return $('.container').append('<div class="warning"><p class="text-error">Please enter some data before your submit!<p></div>');
        }
      });
      $edit.on('click', function() {
        $(this).addClass('disabled');
        $approve.removeClass('disabled');
        $cancel.removeClass('disabled');
        $trash.addClass('disabled');
        $header.html('Edit ' + $header.text());
        return $dds.each(function(val) {
          var $content, $current, $label, $self;

          $self = $(this);
          $label = _.str.trim($self.prev().text());
          $current = $($self[0]).find('>:first-child');
          $content = $current.text();
          if ($label !== 'id') {
            if (_.contains(app.inputRules.txtArea, $label)) {
              app.currentFormData['txt_' + $label] = $content;
              $current.replaceWith('<textarea rows="10" id="txt_' + $label + '"name="' + $label + '" class="span9"/>');
              return $('#txt_' + $label).val($content);
            } else {
              app.currentFormData['input_' + $label] = $content;
              return $current.replaceWith('<input type="text" id="input_' + $label + '"name="' + $label + '" class="span8" value="' + $content + '" />');
            }
          }
        });
      });
      $approve.on('click', function() {
        var $col, $form, $id;

        $edit.removeClass('disabled');
        $(this).addClass('disabled');
        $cancel.addClass('disabled');
        $trash.removeClass('disabled');
        $form = $(this).parents('form:first');
        $col = window.location.pathname.split('/')[window.location.pathname.split('/').length - 2];
        if ($("h3:contains(\"_id\")").length > 0) {
          $id = $("h3:contains(\"_id\")").parent().next().children('.lead').html();
        } else {
          $id = $("h3:contains(\"id\")").parent().next().children('.lead').html();
        }
        return $.ajax({
          type: "PUT",
          url: '/api/' + $col + '/' + $id,
          data: $form.serialize(),
          success: function(data) {
            $dds.each(function(val) {
              var $content, $current, $self;

              $self = $(this);
              $current = $($self[0]).find('>:first-child');
              $content = $current.val();
              if ($current.is('input') || $current.is('textarea')) {
                $current.replaceWith('<p class="lead">' + $content + '</p>');
              }
              if (_.str.include($('#header h2').text(), "Edit")) {
                return $('#header h2').html($('#header h2').text().split('Edit ')[1]);
              }
            });
            return displayStatus('alert-success', 'SUCCESS', 'updated');
          }
        });
      });
      $cancel.on('click', function() {
        $edit.removeClass('disabled');
        $approve.addClass('disabled');
        $(this).addClass('disabled');
        $trash.removeClass('disabled');
        if (_.str.include($('#header h2').text(), "Edit")) {
          $('#header h2').html($('#header h2').text().split('Edit ')[1]);
        }
        $dds.each(function(val) {
          var $content, $current, $self;

          $self = $(this);
          $current = $($self[0]).find('>:first-child');
          $content = app.currentFormData[$current.attr('id')];
          if ($current.is('input') || $current.is('textarea')) {
            return $current.replaceWith('<p class="lead">' + $content + '</p>');
          }
        });
        return displayStatus(null, 'WARNING', 'This update has been cancelled.');
      });
      return $trash.on('click', function() {
        console.log($(this).attr('class'));
        return document.location.href = window.location.pathname.replace('input', 'kill');
      });
    });
  });

}).call(this);
