// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var _ref;

  this.app = (_ref = window.app) != null ? _ref : {};

  define(['jquery'], function($) {
    return app.utils = {
      echo: function(ping) {
        return ping;
      },
      formSerialize: function(formData, e, cb) {
        var $this, child, i, inputs, parent, rslts, _i, _len;

        $this = formData;
        e.preventDefault();
        inputs = $this.find('input[type=text]');
        rslts = {};
        for (_i = 0, _len = inputs.length; _i < _len; _i++) {
          i = inputs[_i];
          if (i.name.indexOf('.') > -1) {
            parent = i.name.split('.')[0];
            child = i.name.split('.')[1];
            if (!rslts[parent]) {
              rslts[parent] = {};
              rslts[parent][child] = i.value;
            }
          } else {
            rslts[i.name] = i.value;
          }
        }
        if (cb) {
          cb(rslts);
        }
        return rslts;
      }
    };
  });

}).call(this);
